import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatCardModule } from '@angular/material/card';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ReceivableCustomer } from '../../../core/models/receivable.model';
import { ReceivableDataService } from '../receivable-service/receivable-data.service';

@Component({
  selector: 'app-receivable-customer-list',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatSnackBarModule
  ],
  templateUrl: './receivable-customer-list.component.html',
  styleUrls: ['./receivable-customer-list.component.css']
})
export class ReceivableCustomerListComponent implements OnInit, OnChanges {
  @Input() receivableId: number | null = null;
  @Input() entities: any[] = [];

  customers: ReceivableCustomer[] = [];
  customerForm!: FormGroup;
  isEditing: boolean = false;
  editingId: number | null = null;
  showForm: boolean = false;

  displayedColumns: string[] = ['entity', 'itemType', 'actions'];

  constructor(
    private fb: FormBuilder,
    private dataService: ReceivableDataService,
    private snackBar: MatSnackBar
  ) {
    this.initForm();
  }

  ngOnInit(): void {
    this.loadCustomers();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['receivableId'] && !changes['receivableId'].firstChange) {
      this.loadCustomers();
    }
  }

  private initForm(): void {
    this.customerForm = this.fb.group({
      id: [null],
      receivablesId: [null],
      entityId: [null, Validators.required],
      itemTypeId: [null]
    });
  }

  loadCustomers(): void {
    if (this.receivableId) {
      this.dataService.getReceivableCustomers(this.receivableId).subscribe({
        next: (customers: ReceivableCustomer[]) => {
          this.customers = customers;
        },
        error: (error: any) => {
          console.error('Error loading customers:', error);
          this.showMessage('Error loading customers');
        }
      });
    }
  }

  onAdd(): void {
    this.showForm = true;
    this.isEditing = false;
    this.editingId = null;
    this.customerForm.reset();
    this.customerForm.patchValue({
      receivablesId: this.receivableId
    });
  }

  onEdit(customer: ReceivableCustomer): void {
    this.showForm = true;
    this.isEditing = true;
    this.editingId = customer.id || null;
    this.customerForm.patchValue(customer);
  }

  onDelete(customer: ReceivableCustomer): void {
    if (confirm('Are you sure you want to delete this customer?')) {
      if (customer.id) {
        this.dataService.deleteReceivableCustomer(customer.id).subscribe({
          next: () => {
            this.showMessage('Customer deleted successfully');
            this.loadCustomers();
          },
          error: (error: any) => {
            console.error('Error deleting customer:', error);
            this.showMessage('Error deleting customer');
          }
        });
      }
    }
  }

  onSubmit(): void {
    if (this.customerForm.valid) {
      const customer: ReceivableCustomer = this.customerForm.value;
      customer.receivablesId = this.receivableId || undefined;

      if (this.isEditing && this.editingId) {
        this.dataService.updateReceivableCustomer(this.editingId, customer).subscribe({
          next: () => {
            this.showMessage('Customer updated successfully');
            this.loadCustomers();
            this.onCancel();
          },
          error: (error: any) => {
            console.error('Error updating customer:', error);
            this.showMessage('Error updating customer');
          }
        });
      } else {
        // Remove id from new records as it's auto-generated by the server
        const { id, ...customerData } = customer;
        this.dataService.addReceivableCustomer(customerData as ReceivableCustomer).subscribe({
          next: () => {
            this.showMessage('Customer added successfully');
            this.loadCustomers();
            this.onCancel();
          },
          error: (error: any) => {
            console.error('Error adding customer:', error);
            this.showMessage('Error adding customer');
          }
        });
      }
    }
  }

  onCancel(): void {
    this.showForm = false;
    this.isEditing = false;
    this.editingId = null;
    this.customerForm.reset();
  }

  getEntityName(entityId: number | undefined): string {
    if (!entityId) return 'N/A';
    const entity = this.entities.find(e => e.id === entityId);
    return entity ? entity.name : 'Unknown';
  }

  private showMessage(message: string): void {
    this.snackBar.open(message, 'Close', {
      duration: 3000,
      horizontalPosition: 'center',
      verticalPosition: 'top'
    });
  }
}
