-- Script was generated by Devart Entity Developer, Version 6.7.965.0
-- Script date 3/18/2026 5:52:31 AM
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Creating a table Payment 
-- 
CREATE TABLE Payment (
   Id INT NOT NULL IDENTITY,
   TrxDate DATETIME2 NOT NULL,
   Amount DECIMAL NOT NULL,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   Remarks NVARCHAR(4000) NOT NULL,
   EntityId INT,
   ItemTypeId INT,
   ItemStatusId INT,
   AdditionalInfo NVARCHAR(4000),
   CONSTRAINT PK_Payment PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Resource 
-- 
CREATE TABLE Resource (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   ItemTypeId INT,
   ItemStatusId INT,
   jsonProperties NVARCHAR(4000),
   CONSTRAINT PK_Resource PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Receivable 
-- 
CREATE TABLE Receivable (
   Id INT NOT NULL IDENTITY,
   TrxRef NVARCHAR(4000) NOT NULL,
   TrxDate DATETIME2 NOT NULL,
   Amount DECIMAL NOT NULL,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   Remarks NVARCHAR(4000) NOT NULL,
   EntityId INT,
   CONSTRAINT PK_Receivable PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Expense 
-- 
CREATE TABLE Expense (
   Id INT NOT NULL IDENTITY,
   TrxDate DATETIME2 NOT NULL,
   Amount DECIMAL NOT NULL,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   Remarks NVARCHAR(4000),
   EntityId INT,
   CONSTRAINT PK_Expense PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table ReceivableStatus 
-- 
CREATE TABLE ReceivableStatus (
   Id INT NOT NULL IDENTITY,
   ReceivableId INT,
   ItemStatusId INT,
   StatusDate DATETIME2 NOT NULL,
   Remarks NVARCHAR(4000),
   CONSTRAINT PK_ReceivableStatus PRIMARY KEY (Id),
   CONSTRAINT FK_ReceivableStatus_Receivable_0 FOREIGN KEY (ReceivableId) REFERENCES Receivable (Id)
)
GO

-- 
-- Creating a table ReceivableCustomer 
-- 
CREATE TABLE ReceivableCustomer (
   Id INT NOT NULL IDENTITY,
   ReceivablesId INT,
   EntityId INT,
   ItemTypeId INT,
   CONSTRAINT PK_ReceivableCustomer PRIMARY KEY (Id),
   CONSTRAINT FK_ReceivableCustomer_Receivable_0 FOREIGN KEY (ReceivablesId) REFERENCES Receivable (Id)
)
GO

-- 
-- Creating a table ExpenseStatus 
-- 
CREATE TABLE ExpenseStatus (
   Id INT NOT NULL IDENTITY,
   ExpenseId INT,
   ItemStatusId INT,
   StatusDate DATETIME2 NOT NULL,
   Remarks NVARCHAR(4000),
   CONSTRAINT PK_ExpenseStatus PRIMARY KEY (Id),
   CONSTRAINT FK_ExpenseStatus_Expense_0 FOREIGN KEY (ExpenseId) REFERENCES Expense (Id)
)
GO

-- 
-- Creating a table JobReceivable 
-- 
CREATE TABLE JobReceivable (
   Id INT NOT NULL IDENTITY,
   ReceivablesId INT,
   JobMainId INT,
   CONSTRAINT PK_JobReceivable PRIMARY KEY (Id),
   CONSTRAINT FK_JobReceivable_Receivable_0 FOREIGN KEY (ReceivablesId) REFERENCES Receivable (Id)
)
GO

-- 
-- Creating a table Timesheet 
-- 
CREATE TABLE Timesheet (
   Id INT NOT NULL IDENTITY,
   tsDate DATETIME2 NOT NULL,
   Remarks NVARCHAR(4000),
   ResourceId INT,
   ResourceId1 INT,
   CONSTRAINT PK_Timesheet PRIMARY KEY (Id),
   CONSTRAINT FK_Timesheet_Resource_0 FOREIGN KEY (ResourceId) REFERENCES Resource (Id),
   CONSTRAINT FK_Timesheet_Resource_1 FOREIGN KEY (ResourceId1) REFERENCES Resource (Id)
)
GO

-- 
-- Creating a table JobTimesheet 
-- 
CREATE TABLE JobTimesheet (
   Id INT NOT NULL IDENTITY,
   TimesheetId INT,
   JobMainId INT,
   CONSTRAINT PK_JobTimesheet PRIMARY KEY (Id),
   CONSTRAINT FK_JobTimesheet_Timesheet_0 FOREIGN KEY (TimesheetId) REFERENCES Timesheet (Id)
)
GO

-- 
-- Creating a table ReceivablePayment 
-- 
CREATE TABLE ReceivablePayment (
   Id INT NOT NULL IDENTITY,
   ReceivablesId INT,
   PaymentsId INT,
   CONSTRAINT PK_ReceivablePayment PRIMARY KEY (Id),
   CONSTRAINT FK_ReceivablePayment_Receivable_0 FOREIGN KEY (ReceivablesId) REFERENCES Receivable (Id),
   CONSTRAINT FK_ReceivablePayment_Payment_1 FOREIGN KEY (PaymentsId) REFERENCES Payment (Id)
)
GO

-- 
-- Creating a table ExpensePayment 
-- 
CREATE TABLE ExpensePayment (
   Id INT NOT NULL IDENTITY,
   ExpensesId INT,
   PaymentsId INT,
   CONSTRAINT PK_ExpensePayment PRIMARY KEY (Id),
   CONSTRAINT FK_ExpensePayment_Expense_0 FOREIGN KEY (ExpensesId) REFERENCES Expense (Id),
   CONSTRAINT FK_ExpensePayment_Payment_1 FOREIGN KEY (PaymentsId) REFERENCES Payment (Id)
)
GO

-- 
-- Creating a table JobServiceTimesheet 
-- 
CREATE TABLE JobServiceTimesheet (
   Id INT NOT NULL IDENTITY,
   TimesheetId INT,
   JobServiceId INT,
   CONSTRAINT PK_JobServiceTimesheet PRIMARY KEY (Id),
   CONSTRAINT FK_JobServiceTimesheet_Timesheet_0 FOREIGN KEY (TimesheetId) REFERENCES Timesheet (Id)
)
GO

