import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatCardModule } from '@angular/material/card';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ReceivableStatus } from '../../../core/models/receivable.model';
import { ReceivableDataService } from '../receivable-service/receivable-data.service';

@Component({
  selector: 'app-receivable-status-list',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSnackBarModule
  ],
  templateUrl: './receivable-status-list.component.html',
  styleUrls: ['./receivable-status-list.component.css']
})
export class ReceivableStatusListComponent implements OnInit, OnChanges {
  @Input() receivableId: number | null = null;
  @Input() itemStatuses: any[] = [];

  statuses: ReceivableStatus[] = [];
  statusForm!: FormGroup;
  isEditing: boolean = false;
  editingId: number | null = null;
  showForm: boolean = false;

  displayedColumns: string[] = ['itemStatus', 'statusDate', 'remarks', 'actions'];

  constructor(
    private fb: FormBuilder,
    private dataService: ReceivableDataService,
    private snackBar: MatSnackBar
  ) {
    this.initForm();
  }

  ngOnInit(): void {
    this.loadStatuses();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['receivableId'] && !changes['receivableId'].firstChange) {
      this.loadStatuses();
    }
  }

  private initForm(): void {
    this.statusForm = this.fb.group({
      id: [null],
      receivableId: [null],
      itemStatusId: [null, Validators.required],
      statusDate: [new Date(), Validators.required],
      remarks: ['']
    });
  }

  loadStatuses(): void {
    if (this.receivableId) {
      this.dataService.getReceivableStatuses(this.receivableId).subscribe({
        next: (statuses: ReceivableStatus[]) => {
          this.statuses = statuses;
        },
        error: (error: any) => {
          console.error('Error loading statuses:', error);
          this.showMessage('Error loading statuses');
        }
      });
    }
  }

  onAdd(): void {
    this.showForm = true;
    this.isEditing = false;
    this.editingId = null;
    this.statusForm.reset();
    this.statusForm.patchValue({
      receivableId: this.receivableId,
      statusDate: new Date()
    });
  }

  onEdit(status: ReceivableStatus): void {
    this.showForm = true;
    this.isEditing = true;
    this.editingId = status.id || null;
    this.statusForm.patchValue(status);
  }

  onDelete(status: ReceivableStatus): void {
    if (confirm('Are you sure you want to delete this status?')) {
      if (status.id) {
        this.dataService.deleteReceivableStatus(status.id).subscribe({
          next: () => {
            this.showMessage('Status deleted successfully');
            this.loadStatuses();
          },
          error: (error: any) => {
            console.error('Error deleting status:', error);
            this.showMessage('Error deleting status');
          }
        });
      }
    }
  }

  onSubmit(): void {
    if (this.statusForm.valid) {
      const status: ReceivableStatus = this.statusForm.value;
      status.receivableId = this.receivableId || undefined;

      if (this.isEditing && this.editingId) {
        this.dataService.updateReceivableStatus(this.editingId, status).subscribe({
          next: () => {
            this.showMessage('Status updated successfully');
            this.loadStatuses();
            this.onCancel();
          },
          error: (error: any) => {
            console.error('Error updating status:', error);
            this.showMessage('Error updating status');
          }
        });
      } else {
        // Remove id from new records as it's auto-generated by the server
        const { id, ...statusData } = status;
        this.dataService.addReceivableStatus(statusData as ReceivableStatus).subscribe({
          next: () => {
            this.showMessage('Status added successfully');
            this.loadStatuses();
            this.onCancel();
          },
          error: (error: any) => {
            console.error('Error adding status:', error);
            this.showMessage('Error adding status');
          }
        });
      }
    }
  }

  onCancel(): void {
    this.showForm = false;
    this.isEditing = false;
    this.editingId = null;
    this.statusForm.reset();
  }

  getItemStatusName(itemStatusId: number | undefined): string {
    if (!itemStatusId) return 'N/A';
    const itemStatus = this.itemStatuses.find(s => s.id === itemStatusId);
    return itemStatus ? itemStatus.name : 'Unknown';
  }

  private showMessage(message: string): void {
    this.snackBar.open(message, 'Close', {
      duration: 3000,
      horizontalPosition: 'center',
      verticalPosition: 'top'
    });
  }
}
