-- Script was generated by Devart Entity Developer, Version 6.7.965.0
-- Script date 5/17/2024 10:04:56 PM
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Creating a table CustStatuses 
-- 
CREATE TABLE CustStatuses (
   Id INT NOT NULL IDENTITY,
   Code NVARCHAR(4000) NOT NULL,
   Display NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   OrderNo NVARCHAR(4000),
   IsActive BIT,
   IsDefault BIT,
   CONSTRAINT PK_CustStatuses PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table CustMains 
-- 
CREATE TABLE CustMains (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000),
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   DtCreated DATETIME2,
   CreatedBy NVARCHAR(4000),
   DtEdited DATETIME2,
   EditedBy NVARCHAR(4000),
   IsActive BIT,
   RecordOrder INT,
   CustStatusId INT,
   CONSTRAINT PK_CustMains PRIMARY KEY (Id),
   CONSTRAINT FK_CustMains_CustStatuses_0 FOREIGN KEY (CustStatusId) REFERENCES CustStatuses (Id)
)
GO

