
@AngularApp1.Server_HostAddress = https://localhost:7129
@AngularApp1.openapi.def = https://localhost:7252/openapi/v1.json

GET {{AngularApp1.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
@AngularApp1.Server_HostAddress = https://localhost:7129
GET {{AngularApp1.Server_HostAddress}}/openapi/v1.json

###
GET {{AngularApp1.openapi.def}}

###
GET {{AngularApp1.Server_HostAddress}}/api/CrLogTrips/today
###
GET {{AngularApp1.Server_HostAddress}}/api/CrLogTrips/5
