-- Script was generated by Devart Entity Developer, Version 6.7.965.0
-- Script date 3/1/2025 6:15:38 PM
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Dropping a table JobServiceContact 
-- 
DROP TABLE JobServiceContact
GO

-- 
-- Dropping a table JobService 
-- 
DROP TABLE JobService
GO

-- 
-- Dropping a table EntityContact 
-- 
DROP TABLE EntityContact
GO

-- 
-- Dropping a table JobCustomer 
-- 
DROP TABLE JobCustomer
GO

-- 
-- Dropping a table JobContact 
-- 
DROP TABLE JobContact
GO

-- 
-- Dropping a table Entity 
-- 
DROP TABLE Entity
GO

-- 
-- Dropping a table Contact 
-- 
DROP TABLE Contact
GO

-- 
-- Dropping a table ServiceItem 
-- 
DROP TABLE ServiceItem
GO

-- 
-- Dropping a table JobInventory 
-- 
DROP TABLE JobInventory
GO

-- 
-- Dropping a table JobMain 
-- 
DROP TABLE JobMain
GO

-- 
-- Dropping a table RefCity 
-- 
DROP TABLE RefCity
GO

-- 
-- Dropping a table ItemStatus 
-- 
DROP TABLE ItemStatus
GO

-- 
-- Dropping a table ItemType 
-- 
DROP TABLE ItemType
GO

-- 
-- Dropping a table RefCountry 
-- 
DROP TABLE RefCountry
GO

-- 
-- Dropping a table BusinessUnit 
-- 
DROP TABLE BusinessUnit
GO

-- 
-- Dropping a table ItemTypeClass 
-- 
DROP TABLE ItemTypeClass
GO

-- 
-- Dropping a table ItemStatusClass 
-- 
DROP TABLE ItemStatusClass
GO

-- 
-- Creating a table ItemStatusClass 
-- 
CREATE TABLE ItemStatusClass (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CONSTRAINT PK_ItemStatusClass PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table BusinessUnit 
-- 
CREATE TABLE BusinessUnit (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CONSTRAINT PK_BusinessUnit PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table ItemTypeClass 
-- 
CREATE TABLE ItemTypeClass (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CONSTRAINT PK_ItemTypeClass PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table RefCountry 
-- 
CREATE TABLE RefCountry (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CONSTRAINT PK_RefCountry PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table ItemStatus 
-- 
CREATE TABLE ItemStatus (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   ItemStatusClassId INT,
   CONSTRAINT PK_ItemStatus PRIMARY KEY (Id),
   CONSTRAINT FK_ItemStatus_ItemStatusClass_0 FOREIGN KEY (ItemStatusClassId) REFERENCES ItemStatusClass (Id)
)
GO

-- 
-- Creating a table RefCity 
-- 
CREATE TABLE RefCity (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CountryId INT,
   RefCountryId INT,
   CONSTRAINT PK_RefCity PRIMARY KEY (Id),
   CONSTRAINT FK_RefCity_RefCountry_0 FOREIGN KEY (RefCountryId) REFERENCES RefCountry (Id)
)
GO

-- 
-- Creating a table ItemType 
-- 
CREATE TABLE ItemType (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   ItemTypeClassId INT,
   CONSTRAINT PK_ItemType PRIMARY KEY (Id),
   CONSTRAINT FK_ItemType_ItemTypeClass_0 FOREIGN KEY (ItemTypeClassId) REFERENCES ItemTypeClass (Id)
)
GO

-- 
-- Creating a table JobMain 
-- 
CREATE TABLE JobMain (
   Id INT NOT NULL IDENTITY,
   JobDate DATETIME2 NOT NULL,
   Description NVARCHAR(4000) NOT NULL,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   ItemStatusId INT,
   BusinessUnitId INT,
   CONSTRAINT PK_JobMain PRIMARY KEY (Id),
   CONSTRAINT FK_JobMain_ItemStatus_0 FOREIGN KEY (ItemStatusId) REFERENCES ItemStatus (Id),
   CONSTRAINT FK_JobMain_BusinessUnit_1 FOREIGN KEY (BusinessUnitId) REFERENCES BusinessUnit (Id)
)
GO

-- 
-- Creating a table JobInventory 
-- 
CREATE TABLE JobInventory (
   Id INT NOT NULL IDENTITY,
   JobMainId INT,
   Particulars NVARCHAR(4000) NOT NULL,
   InvItemsId INT,
   QtyRequired DECIMAL NOT NULL,
   CONSTRAINT PK_JobInventory PRIMARY KEY (Id),
   CONSTRAINT FK_JobInventory_JobMain_0 FOREIGN KEY (JobMainId) REFERENCES JobMain (Id)
)
GO

-- 
-- Creating a table ServiceItem 
-- 
CREATE TABLE ServiceItem (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   ItemTypeId INT,
   ItemStatusId INT,
   CONSTRAINT PK_ServiceItem PRIMARY KEY (Id),
   CONSTRAINT FK_ServiceItem_ItemType_0 FOREIGN KEY (ItemTypeId) REFERENCES ItemType (Id),
   CONSTRAINT FK_ServiceItem_ItemStatus_1 FOREIGN KEY (ItemStatusId) REFERENCES ItemStatus (Id)
)
GO

-- 
-- Creating a table Contact 
-- 
CREATE TABLE Contact (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Remarks NVARCHAR(4000),
   ContactNo1 NVARCHAR(4000),
   ContactNo2 NVARCHAR(4000),
   Address1 NVARCHAR(4000),
   Address2 NVARCHAR(4000),
   Email1 NVARCHAR(4000),
   Email2 NVARCHAR(4000),
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   TypeId INT,
   StatusId INT NOT NULL,
   RefCityId INT,
   CONSTRAINT PK_Contact PRIMARY KEY (Id),
   CONSTRAINT FK_Contact_ItemType_0 FOREIGN KEY (TypeId) REFERENCES ItemType (Id),
   CONSTRAINT FK_Contact_ItemStatus_1 FOREIGN KEY (StatusId) REFERENCES ItemStatus (Id),
   CONSTRAINT FK_Contact_RefCity_2 FOREIGN KEY (RefCityId) REFERENCES RefCity (Id)
)
GO

-- 
-- Creating a table Entity 
-- 
CREATE TABLE Entity (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Description NVARCHAR(4000),
   Remarks NVARCHAR(4000),
   Code NVARCHAR(4000),
   SortOrder INT,
   ContactNo1 NVARCHAR(4000),
   ContactNo2 NVARCHAR(4000),
   Address1 NVARCHAR(4000),
   Address2 NVARCHAR(4000),
   Email1 NVARCHAR(4000),
   Email2 NVARCHAR(4000),
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   EntityTypeId INT,
   EntityStatusId INT,
   BusinessUnitId INT,
   RefCityId INT,
   CONSTRAINT PK_Entity PRIMARY KEY (Id),
   CONSTRAINT FK_Entity_ItemType_0 FOREIGN KEY (EntityTypeId) REFERENCES ItemType (Id),
   CONSTRAINT FK_Entity_ItemStatus_1 FOREIGN KEY (EntityStatusId) REFERENCES ItemStatus (Id),
   CONSTRAINT FK_Entity_BusinessUnit_2 FOREIGN KEY (BusinessUnitId) REFERENCES BusinessUnit (Id),
   CONSTRAINT FK_Entity_RefCity_3 FOREIGN KEY (RefCityId) REFERENCES RefCity (Id)
)
GO

-- 
-- Creating a table JobContact 
-- 
CREATE TABLE JobContact (
   Id INT NOT NULL IDENTITY,
   JobMainId INT,
   ContactId INT,
   IsPrimary BIT NOT NULL,
   Notes NVARCHAR(4000),
   CONSTRAINT PK_JobContact PRIMARY KEY (Id),
   CONSTRAINT FK_JobContact_JobMain_0 FOREIGN KEY (JobMainId) REFERENCES JobMain (Id),
   CONSTRAINT FK_JobContact_Contact_1 FOREIGN KEY (ContactId) REFERENCES Contact (Id)
)
GO

-- 
-- Creating a table JobCustomer 
-- 
CREATE TABLE JobCustomer (
   Id INT NOT NULL IDENTITY,
   JobMainId INT,
   CustomerId INT,
   IsPrimary BIT NOT NULL,
   IsBillTo BIT NOT NULL,
   Notes NVARCHAR(4000),
   CONSTRAINT PK_JobCustomer PRIMARY KEY (Id),
   CONSTRAINT FK_JobCustomer_JobMain_0 FOREIGN KEY (JobMainId) REFERENCES JobMain (Id),
   CONSTRAINT FK_JobCustomer_Entity_1 FOREIGN KEY (CustomerId) REFERENCES Entity (Id)
)
GO

-- 
-- Creating a table EntityContact 
-- 
CREATE TABLE EntityContact (
   Id INT NOT NULL IDENTITY,
   ContactId INT,
   EntityId INT,
   Notes NVARCHAR(4000),
   CONSTRAINT PK_EntityContact PRIMARY KEY (Id),
   CONSTRAINT FK_EntityContact_Contact_0 FOREIGN KEY (ContactId) REFERENCES Contact (Id),
   CONSTRAINT FK_EntityContact_Entity_1 FOREIGN KEY (EntityId) REFERENCES Entity (Id)
)
GO

-- 
-- Creating a table JobService 
-- 
CREATE TABLE JobService (
   Id INT NOT NULL IDENTITY,
   JobMainId INT,
   Particulars NVARCHAR(4000),
   DateStart DATETIME2,
   DateEnd DATETIME2,
   QuotedAmt DECIMAL,
   SupplierAmt DECIMAL,
   CreatedBy NVARCHAR(4000) NOT NULL,
   CreatedOn DATETIME2 NOT NULL,
   LastEditBy NVARCHAR(4000) NOT NULL,
   LastEditOn DATETIME2 NOT NULL,
   isArchived BIT NOT NULL,
   isPrivate BIT NOT NULL,
   isActive BIT NOT NULL,
   ServiceItemId INT,
   SupplierId INT,
   ItemStatusId INT,
   SortOrder INT NOT NULL,
   CONSTRAINT PK_JobService PRIMARY KEY (Id),
   CONSTRAINT FK_JobService_JobMain_0 FOREIGN KEY (JobMainId) REFERENCES JobMain (Id),
   CONSTRAINT FK_JobService_ServiceItem_1 FOREIGN KEY (ServiceItemId) REFERENCES ServiceItem (Id),
   CONSTRAINT FK_JobService_Entity_2 FOREIGN KEY (SupplierId) REFERENCES Entity (Id),
   CONSTRAINT FK_JobService_ItemStatus_3 FOREIGN KEY (ItemStatusId) REFERENCES ItemStatus (Id)
)
GO

-- 
-- Creating a table JobServiceContact 
-- 
CREATE TABLE JobServiceContact (
   Id INT NOT NULL IDENTITY,
   ContactId INT,
   JobServiceId INT,
   Notes NVARCHAR(4000) NOT NULL,
   IsPrimary BIT NOT NULL,
   CONSTRAINT PK_JobServiceContact PRIMARY KEY (Id),
   CONSTRAINT FK_JobServiceContact_Contact_0 FOREIGN KEY (ContactId) REFERENCES Contact (Id),
   CONSTRAINT FK_JobServiceContact_JobService_1 FOREIGN KEY (JobServiceId) REFERENCES JobService (Id)
)
GO

