//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/30/2025 9:06:19 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class Contact {

        public Contact()
        {
            this.ContactInfo = new ContactInfo();
            this.RecordInfo = new RecordInfo();
            this.EntityContacts = new List<EntityContact>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string Remarks
        {
            get;
            set;
        }

        public virtual ContactInfo ContactInfo
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int TypeId
        {
            get;
            set;
        }

        public virtual int StatusId
        {
            get;
            set;
        }

        public virtual int RefCityId
        {
            get;
            set;
        }

        public virtual IList<EntityContact> EntityContacts
        {
            get;
            set;
        }

        public virtual ItemType ItemType
        {
            get;
            set;
        }

        public virtual ItemStatus ItemStatus
        {
            get;
            set;
        }

        public virtual RefCity RefCity
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
