//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/25/2025 9:50:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class JobService {

        public JobService()
        {
            this.RecordInfo = new RecordInfo();
            this.JobServiceContacts = new List<JobServiceContact>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int JobMainId
        {
            get;
            set;
        }

        public virtual string Particulars
        {
            get;
            set;
        }

        public virtual System.DateTime? DateStart
        {
            get;
            set;
        }

        public virtual System.DateTime? DateEnd
        {
            get;
            set;
        }

        public virtual decimal? QuotedAmt
        {
            get;
            set;
        }

        public virtual decimal? SupplierAmt
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int? ServiceItemId
        {
            get;
            set;
        }

        public virtual int? SupplierId
        {
            get;
            set;
        }

        public virtual int ItemStatusId
        {
            get;
            set;
        }

        public virtual int SortOrder
        {
            get;
            set;
        }

        public virtual ServiceItem ServiceItem
        {
            get;
            set;
        }

        public virtual IList<JobServiceContact> JobServiceContacts
        {
            get;
            set;
        }

        public virtual Entity Entity
        {
            get;
            set;
        }

        public virtual ItemStatus ItemStatus
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
