//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/19/2025 9:17:21 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Erp.Domain.Models
{

    public partial class Models : DbContext
    {

        public Models() :
            base()
        {
            OnCreated();
        }

        public Models(DbContextOptions<Models> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Customer> Customers
        {
            get;
            set;
        }

        public virtual DbSet<Contact> Contact
        {
            get;
            set;
        }

        public virtual DbSet<Supplier> Supplier
        {
            get;
            set;
        }

        public virtual DbSet<Customer_Contact> Customer_Contact
        {
            get;
            set;
        }

        public virtual DbSet<Supplier_Contact> Supplier_Contact
        {
            get;
            set;
        }

        public virtual DbSet<RefCity> RefCity
        {
            get;
            set;
        }

        public virtual DbSet<RefCountry> RefCountry
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            this.CustomerMapping(modelBuilder);
            this.CustomizeCustomerMapping(modelBuilder);

            this.ContactMapping(modelBuilder);
            this.CustomizeContactMapping(modelBuilder);

            this.SupplierMapping(modelBuilder);
            this.CustomizeSupplierMapping(modelBuilder);

            this.Customer_ContactMapping(modelBuilder);
            this.CustomizeCustomer_ContactMapping(modelBuilder);

            this.Supplier_ContactMapping(modelBuilder);
            this.CustomizeSupplier_ContactMapping(modelBuilder);

            this.RefCityMapping(modelBuilder);
            this.CustomizeRefCityMapping(modelBuilder);

            this.RefCountryMapping(modelBuilder);
            this.CustomizeRefCountryMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Customer Mapping

        private void CustomerMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().ToTable(@"Customer");
            modelBuilder.Entity<Customer>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Customer>().Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().Property<string>(x => x.Remarks).HasColumnName(@"Remarks").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo1).HasColumnName(@"ContactNo1").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo2).HasColumnName(@"ContactNo2").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address1).HasColumnName(@"Address1").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address2).HasColumnName(@"Address2").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email1).HasColumnName(@"Email1").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email2).HasColumnName(@"Email2").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<int?>(x => x.CityId).HasColumnName(@"CityId").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.CountryId).HasColumnName(@"CountryId").ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.CreatedBy).HasColumnName(@"CreatedBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.LastEditBy).HasColumnName(@"LastEditBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.LastEditOn).HasColumnName(@"LastEditOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isArchived).HasColumnName(@"isArchived").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isPrivate).HasColumnName(@"isPrivate").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isActive).HasColumnName(@"isActive").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().HasKey(@"Id");
        }

        partial void CustomizeCustomerMapping(ModelBuilder modelBuilder);

        #endregion

        #region Contact Mapping

        private void ContactMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Contact>().ToTable(@"Contact");
            modelBuilder.Entity<Contact>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Contact>().Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().Property<string>(x => x.Remarks).HasColumnName(@"Remarks").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo1).HasColumnName(@"ContactNo1").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo2).HasColumnName(@"ContactNo2").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address1).HasColumnName(@"Address1").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address2).HasColumnName(@"Address2").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email1).HasColumnName(@"Email1").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email2).HasColumnName(@"Email2").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<int?>(x => x.CityId).HasColumnName(@"CityId").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.CountryId).HasColumnName(@"CountryId").ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.CreatedBy).HasColumnName(@"CreatedBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.LastEditBy).HasColumnName(@"LastEditBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.LastEditOn).HasColumnName(@"LastEditOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isArchived).HasColumnName(@"isArchived").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isPrivate).HasColumnName(@"isPrivate").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isActive).HasColumnName(@"isActive").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Contact>().HasKey(@"Id");
        }

        partial void CustomizeContactMapping(ModelBuilder modelBuilder);

        #endregion

        #region Supplier Mapping

        private void SupplierMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Supplier>().ToTable(@"Supplier");
            modelBuilder.Entity<Supplier>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Supplier>().Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().Property<string>(x => x.Remarks).HasColumnName(@"Remarks").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo1).HasColumnName(@"ContactNo1").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.ContactNo2).HasColumnName(@"ContactNo2").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address1).HasColumnName(@"Address1").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Address2).HasColumnName(@"Address2").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email1).HasColumnName(@"Email1").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.Email2).HasColumnName(@"Email2").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<int?>(x => x.CityId).HasColumnName(@"CityId").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.ContactInfo).Property<string>(x => x.CountryId).HasColumnName(@"CountryId").ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.CreatedBy).HasColumnName(@"CreatedBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<string>(x => x.LastEditBy).HasColumnName(@"LastEditBy").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<System.DateTime>(x => x.LastEditOn).HasColumnName(@"LastEditOn").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isArchived).HasColumnName(@"isArchived").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isPrivate).HasColumnName(@"isPrivate").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().OwnsOne(t => t.RecordInfo).Property<bool>(x => x.isActive).HasColumnName(@"isActive").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Supplier>().HasKey(@"Id");
        }

        partial void CustomizeSupplierMapping(ModelBuilder modelBuilder);

        #endregion

        #region Customer_Contact Mapping

        private void Customer_ContactMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer_Contact>().ToTable(@"Customer_Contact");
            modelBuilder.Entity<Customer_Contact>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Customer_Contact>().Property<int>(x => x.CustomerId).HasColumnName(@"CustomerId").ValueGeneratedNever();
            modelBuilder.Entity<Customer_Contact>().Property<int>(x => x.ContactId).HasColumnName(@"ContactId").ValueGeneratedNever();
            modelBuilder.Entity<Customer_Contact>().HasKey(@"Id");
        }

        partial void CustomizeCustomer_ContactMapping(ModelBuilder modelBuilder);

        #endregion

        #region Supplier_Contact Mapping

        private void Supplier_ContactMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Supplier_Contact>().ToTable(@"Supplier_Contact");
            modelBuilder.Entity<Supplier_Contact>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Supplier_Contact>().Property<int>(x => x.SupplierId).HasColumnName(@"SupplierId").ValueGeneratedNever();
            modelBuilder.Entity<Supplier_Contact>().Property<int>(x => x.ContactId).HasColumnName(@"ContactId").ValueGeneratedNever();
            modelBuilder.Entity<Supplier_Contact>().HasKey(@"Id");
        }

        partial void CustomizeSupplier_ContactMapping(ModelBuilder modelBuilder);

        #endregion

        #region RefCity Mapping

        private void RefCityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RefCity>().ToTable(@"RefCity");
            modelBuilder.Entity<RefCity>().Property<string>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<RefCity>().Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefCity>().Property<int>(x => x.RefCountryId).HasColumnName(@"RefCountryId").ValueGeneratedNever();
            modelBuilder.Entity<RefCity>().HasKey(@"Id");
        }

        partial void CustomizeRefCityMapping(ModelBuilder modelBuilder);

        #endregion

        #region RefCountry Mapping

        private void RefCountryMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RefCountry>().ToTable(@"RefCountry");
            modelBuilder.Entity<RefCountry>().Property<int>(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<RefCountry>().Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefCountry>().HasKey(@"Id");
        }

        partial void CustomizeRefCountryMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RefCity>().HasOne(x => x.RefCountry).WithMany(op => op.RefCities).IsRequired(true).HasForeignKey(@"RefCountryId");
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
