//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/25/2025 9:50:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class ServiceItem {

        public ServiceItem()
        {
            this.EntityInfo = new EntityInfo();
            this.RecordInfo = new RecordInfo();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual EntityInfo EntityInfo
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int ItemTypeId
        {
            get;
            set;
        }

        public virtual int ItemStatusId
        {
            get;
            set;
        }

        public virtual ItemType ItemType
        {
            get;
            set;
        }

        public virtual ItemStatus ItemStatus
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
