//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/9/2025 10:33:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class ItemStatus {

        public ItemStatus()
        {
            this.EntityInfo = new EntityInfo();
            this.Contacts = new List<Contact>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual EntityInfo EntityInfo
        {
            get;
            set;
        }

        public virtual int ItemStatusClassId
        {
            get;
            set;
        }

        public virtual ItemStatusClass ItemStatusClass
        {
            get;
            set;
        }

        public virtual IList<Contact> Contacts
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
