//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/9/2025 10:33:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class AgentTask {

        public AgentTask()
        {
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual string MonitoredBy
        {
            get;
            set;
        }

        public virtual string performedBy
        {
            get;
            set;
        }

        public virtual string Occurence
        {
            get;
            set;
        }

        public virtual System.DateTime? DueDate
        {
            get;
            set;
        }

        public virtual System.DateTime? ScheduleDate
        {
            get;
            set;
        }

        public virtual string NextReminder
        {
            get;
            set;
        }

        public virtual string OtherInfo
        {
            get;
            set;
        }

        public virtual int AgentTaskStatusId
        {
            get;
            set;
        }

        public virtual AgentTaskStatus AgentTaskStatus
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
