//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/9/2025 10:33:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class RecordInfo {

        public RecordInfo()
        {
            OnCreated();
        }

        public virtual string CreatedBy
        {
            get;
            set;
        }

        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }

        public virtual string LastEditBy
        {
            get;
            set;
        }

        public virtual System.DateTime LastEditOn
        {
            get;
            set;
        }

        public virtual bool isArchived
        {
            get;
            set;
        }

        public virtual bool isPrivate
        {
            get;
            set;
        }

        public virtual bool isActive
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
