//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/30/2025 9:06:19 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class ItemType {

        public ItemType()
        {
            this.EntityInfo = new EntityInfo();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual EntityInfo EntityInfo
        {
            get;
            set;
        }

        public virtual int ItemTypeClassId
        {
            get;
            set;
        }

        public virtual ItemTypeClass ItemTypeClass
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
