//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/25/2025 9:50:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class JobMain {

        public JobMain()
        {
            this.RecordInfo = new RecordInfo();
            this.JobServices = new List<JobService>();
            this.JobCustomers = new List<JobCustomer>();
            this.JobContacts = new List<JobContact>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual System.DateTime JobDate
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int ItemStatusId
        {
            get;
            set;
        }

        public virtual int BusinessUnitId
        {
            get;
            set;
        }

        public virtual IList<JobService> JobServices
        {
            get;
            set;
        }

        public virtual IList<JobCustomer> JobCustomers
        {
            get;
            set;
        }

        public virtual IList<JobContact> JobContacts
        {
            get;
            set;
        }

        public virtual ItemStatus ItemStatus
        {
            get;
            set;
        }

        public virtual BusinessUnit BusinessUnit
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
