//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/19/2025 9:17:21 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class ContactInfo {

        public ContactInfo()
        {
            OnCreated();
        }

        public virtual string ContactNo1
        {
            get;
            set;
        }

        public virtual string ContactNo2
        {
            get;
            set;
        }

        public virtual string Address1
        {
            get;
            set;
        }

        public virtual string Address2
        {
            get;
            set;
        }

        public virtual string Email1
        {
            get;
            set;
        }

        public virtual string Email2
        {
            get;
            set;
        }

        public virtual int? CityId
        {
            get;
            set;
        }

        public virtual string CountryId
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
