//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/9/2025 10:33:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class Agent {

        public Agent()
        {
            this.Agent_instructions = new List<AgentInstruction>();
            this.Agent_bins = new List<AgentBin>();
            this.AgentFeatures = new List<AgentFeature>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual string Roles
        {
            get;
            set;
        }

        public virtual IList<AgentInstruction> Agent_instructions
        {
            get;
            set;
        }

        public virtual IList<AgentBin> Agent_bins
        {
            get;
            set;
        }

        public virtual IList<AgentFeature> AgentFeatures
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
