//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/9/2025 10:33:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class JobCustomer {

        public JobCustomer()
        {
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int JobMainId
        {
            get;
            set;
        }

        public virtual int CustomerId
        {
            get;
            set;
        }

        public virtual bool IsPrimary
        {
            get;
            set;
        }

        public virtual bool IsBillTo
        {
            get;
            set;
        }

        public virtual string Notes
        {
            get;
            set;
        }

        public virtual Entity Entity
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
