//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/25/2025 9:50:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Erp.Domain.Models
{
    public partial class Entity {

        public Entity()
        {
            this.EntityInfo = new EntityInfo();
            this.ContactInfo = new ContactInfo();
            this.RecordInfo = new RecordInfo();
            this.EntityContacts = new List<EntityContact>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual EntityInfo EntityInfo
        {
            get;
            set;
        }

        public virtual ContactInfo ContactInfo
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int EntityTypeId
        {
            get;
            set;
        }

        public virtual int EntityStatusId
        {
            get;
            set;
        }

        public virtual int BusinessUnitId
        {
            get;
            set;
        }

        public virtual int RefCityId
        {
            get;
            set;
        }

        public virtual IList<EntityContact> EntityContacts
        {
            get;
            set;
        }

        public virtual ItemType ItemType
        {
            get;
            set;
        }

        public virtual ItemStatus ItemStatus
        {
            get;
            set;
        }

        public virtual BusinessUnit BusinessUnit
        {
            get;
            set;
        }

        public virtual RefCity RefCity
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
