//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/18/2024 12:42:36 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Entities
{
    public partial class CustMain {

        public CustMain()
        {
            this.DataInfo = new DataInfo();
            this.RecordInfo = new RecordInfo();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual DataInfo DataInfo
        {
            get;
            set;
        }

        public virtual RecordInfo RecordInfo
        {
            get;
            set;
        }

        public virtual int CustStatusId
        {
            get;
            set;
        }

        public virtual CustStatus CustStatus
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
