//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/18/2024 12:42:36 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Entities
{
    public partial class ReferenceInfo {

        public ReferenceInfo()
        {
            OnCreated();
        }

        public virtual string? Code
        {
            get;
            set;
        }

        public virtual string? Display
        {
            get;
            set;
        }

        public virtual string? Remarks
        {
            get;
            set;
        }

        public virtual string? OrderNo
        {
            get;
            set;
        }

        public virtual bool? IsActive
        {
            get;
            set;
        }

        public virtual bool? IsDefault
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
